SELECT * FROM supply_chain__data.supply_chain_data;
alter table supply_chain_data
drop column MyUnknownColumn;
-- 1. Revenue by Product Type
-- Write an SQL query to calculate the total revenue generated for each Product type and rank them from highest to lowest.

select Producttype,
	sum(Revenue_generated) as total_revenue,
    rank() over(

		order by sum(Revenue_generated)desc) as revenue_rank

from supply_chain_data
group by Producttype
order by total_revenue desc;

-- 2. Identify High-Defect SKUs
-- Write a query to list all SKUs where the Defect rate is greater than
 -- 3%, along with their supplier and transportation mode.

select SKU,
	   Defect_rates,
       Supplier_name,
       Transportation_modes
from supply_chain_data
where Defect_rates > 3
order by Defect_rates desc;

-- 3. Supplier Performance – Lead Time Analysis
-- Write a query to compute the average Lead time for each supplier 
-- and identify which supplier has the highest average lead time.

 select Supplier_name,
		avg(Lead_times) as avg_lead_time
from supply_chain_data
group by Supplier_name
order by avg_lead_time desc;

-- 4. Shipping Cost by Carrier
-- Write a query to calculate the total shipping cost handled by each Shipping
-- carrier and find the top 3 most expensive carriers.

select Shipping_carriers,
	   sum(Shipping_costs) as total_shipping_cost
from supply_chain_data
group by Shipping_carriers
order by total_shipping_cost desc
limit 3;

-- 5. Identify SKUs Below Category Average Price
-- Write a query to return SKUs where the Price is 
-- below the Category Avg, grouped by product type.

select SKU,
	   Producttype,
       avg(Price) over                                                       
       (partition by Producttype)
       as category_avg_price
from supply_chain_data
where Price < (select avg(s2.Price)
			   from supply_chain_data s2
               where s2.Producttype = supply_chain_data.Producttype)
order by Producttype, Price;

-- 6. Transportation Mode Usage
-- Write a query to count how many SKUs use each Transportation mode
--  (Road, Air, Rail, Sea) and calculate their percentage share.

select Transportation_modes,
	   count(SKU) as total_skus,
       round(
       (count(SKU)* 100)/
       (select count(*) from supply_chain_data),
       2)
       as percentage_share
from supply_chain_data
group by Transportation_modes
order by total_skus desc;

-- 7. Top 10 SKUs by Revenue
-- Write a query to list the top 10 SKUs with the highest revenue,
--  including product type, supplier, and shipping carrier.

select sku,
       Revenue_generated,
       Producttype,
       Supplier_name,
       Shipping_carriers
from supply_chain_data
order by Revenue_generated desc limit 10;
	   
-- 8. Lead Time vs Manufacturing Lead Time Gap
-- Write a query to calculate the difference between Lead time
--  and Manufacturing lead time for each SKU and identify SKUs where the gap exceeds 20 days.

select
	SKU,
    Lead_time,
    Manufacturing_lead_time,
    (Lead_time-Manufacturing_lead_time) as lead_time_gap
from supply_chain_data
WHERE(Lead_time-Manufacturing_lead_time) > 20
order by lead_time_gap desc;

-- 9. Customer Demographics Revenue Contribution
-- Write a query to compute total revenue generated by each Customer
-- demographic group (Male, Female, Non-binary, Unknown).

select
	Customer_demographics,
    sum(Revenue_generated) as total_revenue
from supply_chain_data
group by Customer_demographics
order by total_revenue desc;

-- 10. Route-Level Logistics Cost Analysis
-- Write a query to calculate the average logistics Cost per 
-- Route and identify which route is the most expensive.

select 
	Routes,
    avg(Costs) as avg_logistics_cost
from supply_chain_data
group by Routes
order by avg_logistics_cost desc;
    
